import type { SiteContent } from './types'

export const defaultSiteContent: SiteContent = {
  appName: 'Kartograf',
  tagline: 'Топографический архив',
  contactEmail: 'support@kartograf.app',
  feedbackSubject: 'Обратная связь Kartograf',
  copyright: '© 2026 Kartograf',
  header: {
    currentUserAria: 'Текущий пользователь',
    defaultUserName: 'Пользователь',
    adminRole: 'Администратор',
    userRole: 'Пользователь',
    profile: 'Профиль',
    admin: 'Панель управления',
    logout: 'Выйти',
    login: 'Войти в аккаунт',
  },
  footer: {
    links: [
      { id: 'about', label: 'О проекте' },
      { id: 'sources', label: 'Источники карт' },
      { id: 'licenses', label: 'Права и лицензии' },
      { id: 'feedback', label: 'Обратная связь' },
    ],
  },
  home: {
    eyebrow: 'Историческая картография',
    title: 'Сравнивайте старые карты с современной подложкой.',
    text: 'Откройте рабочее пространство карты, управляйте прозрачностью слоя, сохраняйте точки и работайте с каталогом архивных карт.',
    mapCard: {
      eyebrow: 'Основной вход',
      title: 'Открыть карту',
      text: 'Карта доступна сразу. Войдите позже, если нужно сохранять точки и скачивать архивы.',
      authenticatedText: 'Перейдите к карте, чтобы выбрать архивный слой, сравнить его с подложкой и работать с точками.',
      primaryAction: 'Открыть карту',
      secondaryAction: 'Войти',
    },
    catalogCard: {
      eyebrow: 'Каталог',
      title: 'Каталог карт',
      text: 'Просматривайте каталог, выбирайте нужный год, сверяйте описания и открывайте нужный лист прямо на карте.',
      primaryAction: 'Каталог карт',
      secondaryAction: 'Профиль',
    },
    adminCard: {
      eyebrow: 'Администрирование',
      title: 'Управление картами',
      text: 'Загрузка новых архивов, обновление метаданных и управление каталогом.',
      primaryAction: 'Открыть панель',
    },
  },
  staticPages: {
    about: {
      eyebrow: 'О проекте',
      title: 'О проекте',
      intro: 'Краткое описание сервиса, назначения и сценариев использования.',
      markdownUrl: '/content/pages/about.md',
      fallbackMarkdown: '# О проекте\n\nKartograf — сервис для просмотра исторических карт и сравнения их с современной подложкой.',
    },
    sources: {
      eyebrow: 'Источники',
      title: 'Источники карт',
      intro: 'Информация о происхождении карт и ссылках на архивы.',
      markdownUrl: '/content/pages/sources.md',
      fallbackMarkdown: '# Источники карт\n\nСведения об источниках конкретных карт указываются в карточках карт.',
    },
    licenses: {
      eyebrow: 'Правовая информация',
      title: 'Права и лицензии',
      intro: 'Правила использования материалов и ответственность пользователя.',
      markdownUrl: '/content/pages/licenses.md',
      fallbackMarkdown: '# Права и лицензии\n\nСведения о правах конкретных карт указываются в карточках карт. Перед любыми полевыми работами убедитесь, что поиск и земляные работы разрешены в выбранном месте.',
    },
    feedback: {
      eyebrow: 'Связь',
      title: 'Обратная связь',
      intro: 'Куда писать об ошибках в описании, источниках, правах или привязке.',
      markdownUrl: '/content/pages/feedback.md',
      fallbackMarkdown: '# Обратная связь\n\nЕсли вы нашли ошибку в описании карты, источнике, правах или привязке, напишите нам.',
    },
  },
  workspace: {
    fallbackMapTitle: 'Карты',
    fallbackMapDescription: 'Выберите подложку и откройте карту из каталога.',
    selectedMapDescriptionTemplate: 'Исторический слой для карты «{slug}».',
    backToHome: '← Назад',
    overlayLabel: 'Слой карты',
    overlayTitle: 'Прозрачность',
    overlaySelectedTemplate: 'Слой для карты «{title}».',
    overlayEmptyHint: 'Выберите карту в каталоге, чтобы показать исторический слой.',
    basemapLabel: 'Подложка',
    catalogLabel: 'Каталог карт',
    catalogSearchLabel: 'Поиск по каталогу',
    catalogSearchPlaceholder: 'Название или slug',
    mapsLoading: 'Загружаем каталог...',
    mapsEmpty: 'Пока нет доступных карт.',
    mapsNoResults: 'По этому запросу ничего не найдено.',
    mapYearUnknown: 'Год не указан',
    mapDescriptionEmpty: 'Описание карты пока не заполнено.',
    mapToggleCollapse: 'Свернуть',
    mapToggleExpand: 'Подробнее',
    mapToggleCollapseAria: 'Свернуть карточку карты',
    mapToggleExpandAria: 'Развернуть карточку карты',
    mapDetailYear: 'Год',
    mapDetailStatus: 'Статус',
    mapStatusSelected: 'Выбрана',
    mapStatusAvailable: 'Доступна',
    downloadPending: 'Готовим...',
    downloadAction: 'Скачать архив',
    pointsToggleAria: 'Открыть панель точек',
    pointsToggle: 'Точки',
    pointsEyebrow: 'Точки',
    pointsTitle: 'Мои точки',
    pointsClose: 'Скрыть',
    pointsCloseAria: 'Свернуть панель точек',
    pointsLoading: 'Загружаем точки...',
    pointsEmptyTitle: 'Пока нет сохранённых точек',
    pointsEmptyText: 'Кликните правой кнопкой по карте, чтобы добавить новую точку.',
    pointDescriptionEmpty: 'Описание не заполнено.',
    pointCreateTitle: 'Новая точка',
    pointEditTitle: 'Редактирование точки',
    pointSave: 'Сохранить',
    pointDownloadError: 'Не удалось начать скачивание.',
    pointsLoadError: 'Не удалось загрузить точки.',
    mapsLoadError: 'Не удалось загрузить каталог карт.',
  },
}